Add requirements, package setup and docs

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,35 +6,87 @@ on:
 
 jobs:
   check:
+    strategy:
+      matrix:
+        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
+
     runs-on: ubuntu-latest
 
     steps:
       - uses: actions/checkout@v4
       - uses: "opensafely-core/setup-action@v1"
         with:
-          python-version: "3.11"
+          python-version: ${{ matrix.python-version }}
           install-just: true
       - name: Check formatting, linting and import sorting
         run: just check
 
   test:
+    strategy:
+      matrix:
+        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
+
     runs-on: ubuntu-latest
 
     steps:
       - uses: actions/checkout@v4
       - uses: "opensafely-core/setup-action@v1"
         with:
-          python-version: "3.11"
+          python-version: ${{ matrix.python-version }}
           install-just: true
       - name: Run tests
-#       env:  # Add environment variables required for tests
         run: |
           just test
 
-  lint-dockerfile:
+  test-package-build:
+    strategy:
+      matrix:
+        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
+
     runs-on: ubuntu-latest
+
+    name: Test we can build a Python package
     steps:
       - uses: actions/checkout@v4
-      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf  # v3.1.0
         with:
-          failure-threshold: error
+          fetch-depth: 0
+      - uses: "opensafely-core/setup-action@v1"
+        with:
+          python-version: ${{ matrix.python-version }}
+          install-just: true
+
+      - name: Check the wheel installs and runs
+        run: just package-test wheel
+
+      - name: Check the sdist installs and runs
+        run: just package-test sdist
+
+  tag-new-version:
+    needs: [check, test, test-package-build]
+    runs-on: ubuntu-latest
+
+    if: github.ref == 'refs/heads/main'
+
+    steps:
+      - uses: actions/checkout@v4
+      - name: Tag new release
+        run: |
+          # ignore failures here to avoid merges into main without version
+          # bumps failing this job.
+          git tag "v$(cat version)" || exit
+          git push --tags
+
+  required-checks:
+    if: always()
+
+    needs:
+    - check
+    - test
+
+    runs-on: Ubuntu-latest
+
+    steps:
+    - name: Decide whether the needed jobs succeeded or failed
+      uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe  # v1.2.2
+      with:
+        jobs: ${{ toJSON(needs) }}
